// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsJ4OQXSYyfdy32YUxGDm0fL32e81WGgo',
    appId: '1:42287571424:web:20c8785b56ff9e7a330b85',
    messagingSenderId: '42287571424',
    projectId: 'nebengyuk-7129f',
    authDomain: 'nebengyuk-7129f.firebaseapp.com',
    storageBucket: 'nebengyuk-7129f.firebasestorage.app',
    measurementId: 'G-W1R11QXLJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOyjDCqnjOsm-B0RCxcfUgIW-Og95pWwg',
    appId: '1:42287571424:android:ba4b1dbfdda11b8e330b85',
    messagingSenderId: '42287571424',
    projectId: 'nebengyuk-7129f',
    storageBucket: 'nebengyuk-7129f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQEGZziCbCF80CFPXgihD1BUBEwuxxDb0',
    appId: '1:42287571424:ios:2064c47fce1adada330b85',
    messagingSenderId: '42287571424',
    projectId: 'nebengyuk-7129f',
    storageBucket: 'nebengyuk-7129f.firebasestorage.app',
    iosBundleId: 'com.example.nebengyuk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQEGZziCbCF80CFPXgihD1BUBEwuxxDb0',
    appId: '1:42287571424:ios:2064c47fce1adada330b85',
    messagingSenderId: '42287571424',
    projectId: 'nebengyuk-7129f',
    storageBucket: 'nebengyuk-7129f.firebasestorage.app',
    iosBundleId: 'com.example.nebengyuk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsJ4OQXSYyfdy32YUxGDm0fL32e81WGgo',
    appId: '1:42287571424:web:81d1aa1ed6b49d7a330b85',
    messagingSenderId: '42287571424',
    projectId: 'nebengyuk-7129f',
    authDomain: 'nebengyuk-7129f.firebaseapp.com',
    storageBucket: 'nebengyuk-7129f.firebasestorage.app',
    measurementId: 'G-SCQY1JVD5T',
  );
}
